- name: Format standard data disks
  become: true
  filesystem:
    dev: "{{ item.devices[0] }}"
    fstype: '{{ item.fs_type }}'
    opts: '{{ item.fs_options | default(None) }}'
  with_items: '{{ data_disks }}'
  when:
    - (item.type is not defined) or
      (item.type == 'standard')
    - item.devices|length == 1

- name: Get UUID of standard disks
  become: true
  command: blkid -s UUID -o value "{{ item.devices[0] }}"
  changed_when: false
  register: data_disks_standard_blkid
  with_items: '{{ data_disks }}'
  when:
    - (item.type is not defined) or
      (item.type == 'standard')

- name: Configure systemd unit files for standard disks
  become: true
  template:
    dest: "/etc/systemd/system/{{ item.0.path[1:] | replace('/', '-') }}.mount"
    src: templates/mount-unit.j2
  with_together:
    - '{{ data_disks }}'
    - '{{ data_disks_standard_blkid.results }}'
  when:
    - ansible_service_mgr == 'systemd'
    - (item.0.type is not defined) or
      (item.0.type == 'standard')
  register: systemd_mount_config

- name: Enable/start systemd units for standard disks
  become: true
  systemd:
    name: "{{ item.path[1:] | replace('/', '-') }}.mount"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items: '{{ data_disks }}'
  when:
    - ansible_service_mgr == 'systemd'
    - (item.type is not defined) or
      (item.type == 'standard')
