---
- name: Block create and format standard data disk with partitions
  include_tasks: standard-partitions.yml
  loop: '{{ data_disks }}'
  loop_control: 
    loop_var: data_disk
  when:
    - (data_disk.partitions is defined)
    - (data_disk.type is not defined) or
      (data_disk.type == 'standard')
    - data_disk.devices|length == 1

- name: Block format standard data disks
  include_tasks: standard-fulldisk.yml
  loop: '{{ data_disks }}'
  loop_control: 
    loop_var: data_disk
  when:
    - (data_disk.partitions is not defined)
    - (data_disk.type is not defined) or
      (data_disk.type == 'standard')
    - data_disk.devices|length == 1

